### ISSUE TITLE
console warning when chat view is presented.

### ISSUE THREAD

**Issue by pprevalon1** [exyte/Chat#28] opened 2023-08-16 01:55 UTC
I get the following warning in my console is there a fix for this
<img width="689" alt="image" src="https://github.com/exyte/Chat/assets/128199596/fa83d138-40de-473d-811c-fa054e96c114">

**Comment by f3dm76** [comment] 2023-08-25 08:49
Hey @pprevalon1, which version of xcode, ChatView and ios simulator are you using? Could you please make sure the issue is still present in the latest version 1.1.0, and provide some details so I can reproduce the warning. Have great day!

**Comment by f3dm76** [comment] 2023-10-20 06:19
Hey @pprevalon1, I've seen the warning and I think I fixed with assigning a priority to the queue, please check out version 1.2.1

**Closed by f3dm76** 2023-10-20 06:19 UTC
