### ISSUE TITLE
Get a crash every time I append a new message 

### ISSUE THREAD

**Issue by byaruhaf** [exyte/Chat#40] opened 2023-11-02 07:29 UTC
I get the error below every time I append messages

```swift
@Observable
class AblyServiceManager  {
    var allUsers: Set<User> = []
    var messages: [Message] = []

func addNewMSG {
messages.append(newMSG)
}
}
```

```
*** Assertion failure in -[UITableView _Bug_Detected_In_Client_Of_UITableView_Invalid_Number_Of_Rows_In_Section:], UITableView.m:2,611
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (2) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <UITableView: 0x10b11e000; frame = (0 0; 430 718); transform = [-1, 1.2246467991473532e-16, -1.2246467991473532e-16, -1, 0, 0]; clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600000cf7510>; backgroundColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x6000003248c0>; contentOffset: {0, 0}; contentSize: {429.99999999999989, 103.43333206176757}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <_TtGCV9ExyteChat6UIList11CoordinatorV7SwiftUI9EmptyView__: 0x60000330b2a0>>'
*** First throw call stack:

```

**Comment by f3dm76** [comment] 2023-11-02 07:33
Hey @byaruhaf, do you have the latest version 1.2.2? If yes, what is your ios and xcode versions?

**Comment by f3dm76** [comment] 2023-11-02 10:16
@byaruhaf, could you please provide your code? Because I am running example project, which appends new messages by timer, and I get no crashes

**Comment by byaruhaf** [comment] 2023-11-02 12:39
@f3dm76  will do

**Comment by slimshadystark** [comment] 2023-11-06 18:17
Hello @f3dm76 , same problem here. Adding messages does not make the app crash but scrolling to top of the list does, following the error:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid batch updates detected: the number of sections and/or rows returned by the data source before and after performing the batch updates are inconsistent with the updates.
Data source before updates = { 2 sections with row counts: [28, 1] }
Data source after updates = { 2 sections with row counts: [26, 1] }
Updates = [
	Delete row (0 - 0)
]
Table view: <UITableView: 0x126081000; frame = (-1.41015e-15 0; 428 393); transform = [-1, 1.2246467991473532e-16, -1.2246467991473532e-16, -1, 0, 0]; clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x281eeb870>; backgroundColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x2810723c0>; contentOffset: {0, 1011}; contentSize: {427.99999999999994, 1311.1999961853023}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <_TtGCV9ExyteChat6UIList11CoordinatorV7SwiftUI9EmptyView__: 0x282107e80>>'`

**Comment by f3dm76** [comment] 2023-11-07 02:36
Guys @byaruhaf and @slimshadystark, please show me the code - how to reproduce the issue. Nothing crashes for me in example projects, neither when I append nor when I scroll to top. I see your crashes are in UIList.swift, but I cannot reproduce them. Please attach a reproducible scenario, it could be a simple modification of one of the example projects or your own simplified project in archive.

**Comment by irangareddy** [comment] 2023-11-11 12:49
Certainly! Here's a clear explanation of the issue:

Hi @f3dm76,

I'm encountering a bug, and I believe I've identified its cause. Let's consider the scenario where user A is sending messages to user B. If user B is inactive and hasn't sent any messages, user A's view models only reflect the changes made by user A. However, when user B is active and sending messages simultaneously, the message count exceeds the actual count.

This inconsistency leads to an 'NSInternalInconsistencyException' with the following details:

```text
Invalid batch updates detected: the number of sections and/or rows returned by the data source before and after performing the batch updates are inconsistent with the updates.

Data source before updates = { 1 section with row counts: [26] }
Data source after updates = { 1 section with row counts: [22] }

Updates = [
    Delete row (0 - 25),
    Delete row (0 - 23),
    Delete row (0 - 0)
]
```

It seems like the batch updates are not aligned with the actual data source changes, causing this exception. I would appreciate any insights or suggestions you might have to resolve this issue.

## Reproducible Code

### View
```swift
struct PrivateMessagesView: View {
    @State private var scrollToBottom = false
    @StateObject private var globalFocusState = GlobalFocusState()
    @StateObject private var viewModel = PrivateMessageViewModel()

    @State var message = ""
    @State var isEditing: Bool = false
    @State var chat: PrivateMessage
    var fromChats: Bool = false

    var body: some View {
        AsyncContentView(source: viewModel) { _ in
            ZStack {
                ChatView(messages: viewModel.messages) { draft in
                    Task {
                        if let imageMedia = draft.medias.first, imageMedia.type == .image {
                            do {
                                let attachment = await imageMedia.getData()
                                let imageData = UIImage(data: attachment!)?.jpegData(compressionQuality: 0.5)
                                let message = draft.text

                                // Now you have the image data in the `imageData` variable
                                sendMessage(message: message, attachment: imageData)
                            }
                        } else {
                            let message = draft.text
                            sendMessage(message: message)
                        }
                    }
                }
                //                .enableLoadMore(offset: 3) { message in
                //                    viewModel.loadMoreMessages(user: chat.receiver.data!.id)
                //
                //                   }
                .setMediaPickerSelectionParameters(.init(mediaType: .photo))
                .messageUseMarkdown(messageUseMarkdown: true)
                .chatNavigation(
                    title: chat.isSender ? chat.receiver.data!.userName : chat.sender.data!.userName,
                    status: "online",
                    cover: (chat.isSender ? chat.receiver.data : chat.sender.data)?.avatarURL ?? static_user_details.avatarURL
                )
                .toolbar {
                    ToolbarItem(placement: .topBarTrailing) {
                        Button(action: {
                            // Handle the action that triggers the context menu
                        }) {
                            Label("Options", systemImage: "ellipsis.circle")
                        }
                        .contextMenu {
                            Button(action: {
                                // Handle the "Remove" action
                            }) {
                                Label("Remove", systemImage: "trash")
                            }

                            Button(action: {
                                // Handle the "Report" action
                            }) {
                                Label("Report", systemImage: "flag")
                            }
                        }
                    }

                }

                .navigationBarTitleDisplayMode(.inline)
                .chatTheme(spiceitupChatTheme)
            }.padding(8)
            .redacted(reason: !viewModel.messages.isEmpty ? [] : .placeholder)
            .onReceive(viewModel.messages.publisher, perform: { _ in
                scrollToBottom = true
            })
            .onAppear {
                viewModel.getMessages(user: chat.isSender ? chat.receiver.data!.id : chat.sender.data!.id, page: 1)
            }
            .onReceive(viewModel.$chat) { newChat in
                chat = newChat ?? chat
                scrollToBottom = true
            }.fullYellowBackground()
        }
    }

    private func sendMessage(message: String, attachment: Data? = nil) {
        var modifiedMessage = SendMessage(
            receiverType: SendMessageType.user.rawValue,
            receiverID: chat.isSender ? chat.receiver.data!.id : chat.sender.data!.id,
            text: message,
            file: attachment
        )

        // Modify the message based on chat.isSender
        if !chat.isSender {
            // Assuming chat.sender.data can be nil
            if let senderData = chat.sender.data {
                modifiedMessage = SendMessage(
                    receiverType: SendMessageType.user.rawValue,
                    receiverID: senderData.id,
                    text: message,
                    file: attachment
                )
            }
        }

        // Replace User with the actual user object you want to use as the currentUser
        let currentUser = chat.sender.data?.toChatUser(isCurrentUser: true)

        viewModel.sendMessage(with: modifiedMessage, currentUser: currentUser!)
    }

}
```

### ViewModel
```swift
class PrivateMessageViewModel: LoadableObject {

    typealias Output = Any
    typealias XMessage = ExyteChat.Message
    private var cancellables = Set<AnyCancellable>()
    let spiceup = SpiceUpAPI()

    static let shared: PrivateMessageViewModel = PrivateMessageViewModel()
    @Published private(set) var state = LoadingState<Output>.idle
    @Published var messages: [XMessage] = [] {
        didSet {
            objectWillChange.send()
        }
    }
    @Published var chat: PrivateMessage?
    private var currentPage: Int = 0
    private var totalPages: Int = 10

    init() {
        self.onAppear()
    }

    func getMessages(user id: Int, page count: Int) {
        let promise = spiceup.getPrivateMessages(user: id, page: count)

        PromiseHandler<PrivateMessages>.fulfill(promise, storedIn: &cancellables) { [self] result in
            switch result {
            case .success(let response):
                let chatMessages = response.data.data.reversed().compactMap { privateMessage in
                    if let filePath = privateMessage.filePath {
                        let attachmentURL = URL(string: IMAGE_SITE + filePath)
                        return privateMessage.toAttachmentChatMessage(image: (attachmentURL ?? URL(string: DEFAULT_PICTURE))!)
                    }
                    return privateMessage.toPlainChatMessage()
                }
                self.messages = chatMessages

                if self.messages.isEmpty {
                    //                    sendMessage(with: SendMessage(receiverType: SendMessageType.user.rawValue, receiverID: id, text: "Hey there!"), currentUser: SpiceUpAPI.getUserId())
                    // TODO: Handle of No Messages
                }
                self.chat = response.data.data.reversed().last
            case .failure(let error):
                self.state = .failed(error)
            }
        }
    }

    func onAppear() {
        self.state = LoadingState.loaded(Void.self)
    }
    func onFailure() {
        self.state = LoadingState.loaded(Void.self)
    }

}

extension PrivateMessageViewModel {
    func sendMessage(with message: SendMessage, currentUser: ExyteChat.User) {
        let privateXMessage = XMessage(id: UUID().uuidString, user: currentUser, status: .sending, createdAt: Date(), text: message.text)
        messages.append(privateXMessage)

        // Create parameters for the message
        let params: [String: CustomStringConvertible] = [
            "receiver_type": message.receiverType,
            "receiver_id": message.receiverID,
            "text": message.text
        ]

        // Create an empty array to hold multipart data
        var multipartData: [MultipartData] = []

        // Check if a file is attached to the message
        if let fileData = message.file {
            let file = MultipartData(name: "file", fileData: fileData, fileName: "attachment.jpg", mimeType: "image/jpeg")
            multipartData.append(file)
        }

        // Send the message with or without the file attachment
        var promise: AnyPublisher<(Data?, Progress), Error>
        if !multipartData.isEmpty {
            promise = spiceup.sendMessage(params: params, multipart: multipartData)
        } else {
            promise = spiceup.sendMessage(params: params, multipart: [])
        }

        promise
            .map { _ in }
            .receive(on: DispatchQueue.main)  // Ensure UI updates on the main thread
            .sink(receiveCompletion: { completion in
                switch completion {
                case .finished:
                    break
                case .failure(let error):
                    self.state = .failed(error)
                }
            }) { _ in
                // Handle the message sent successfully
                self.state = .loaded(Void.self)
                self.getMessages(user: message.receiverID, page: 1)
            }
            .store(in: &cancellables)
    }
}

extension Sequence {
    func asyncMap<T>(
        _ transform: (Element) async throws -> T
    ) async rethrows -> [T] {
        var values = [T]()

        for element in self {
            try await values.append(transform(element))
        }

        return values
    }
}

// TODO: Load More
extension PrivateMessageViewModel {

    // Add a method to fetch more messages
    func loadMoreMessages(user id: Int) {
        // Check if there are more pages to load
        if currentPage <= totalPages {
            // Increment the currentPage to fetch the next page of messages
            currentPage += 1

            let promise = spiceup.getPrivateMessages(user: id, page: currentPage)

            PromiseHandler<PrivateMessages>.fulfill(promise, storedIn: &cancellables) { [self] result in
                switch result {
                case .success(let response):
                    let chatMessages = response.data.data.compactMap { privateMessage in
                        if let filePath = privateMessage.filePath {
                            let attachmentURL = URL(string: IMAGE_SITE + filePath)
                            return privateMessage.toAttachmentChatMessage(image: (attachmentURL ?? URL(string: DEFAULT_PICTURE))!)
                        }
                        return privateMessage.toPlainChatMessage()
                    }

                    // Append the new messages to the existing messages array
                    messages.append(contentsOf: chatMessages)

                    // Update the totalPages
                    totalPages = response.data.meta.pagination.totalPages
                case .failure(let error):
                    self.state = .failed(error)
                    currentPage -= 1
                }
            }
        }
    }
}
```

**Comment by iamxvbaba** [comment] 2023-11-13 08:37
I have had type problems before. My reason is that the message ID is not unique. You can refer to it.

**Comment by f3dm76** [comment] 2023-11-16 06:32
Hey @irangareddy, thank you very much for the code, but it doesn't compile due to multiple classing missing (PromiseHandler, PrivateMessage, AsyncContentView, and so on). Please provide an archive of a working project or a fully compilable code sample.

I must admit I don't understand the issue you are trying to explain.
>user A is sending messages to user B. If user B is inactive and hasn't sent any messages, user A's view models only reflect the changes made by user A. However, when user B is active and sending messages simultaneously, the message count exceeds the actual count.
So I need to send messages simultaneously from A and B? I did that and didn't see the crash. Do I need to send message from A and B in exactly the same instant? Could you please provide exact steps for reproduction?

The insights: The crash is clearly happening in UIList.swift file, where UITableView is trying to correctly animate messages insertion. The thing is insertions and removals should be animated and updates (like status change to delivered) - not animated. That is why all the changes are split into insertions, removals and edits and applied manually in batches to data source and UITableView both. This caused a lot of problems, but since version 1.2.3 I didn't see any of them anymore. There are commented out logs which help spell out all the steps which are happening in UIList, please uncomment them if you'd like to give it a go and try and debug the issue.

Have a wonderful day!

**Comment by froggomad** [comment] 2023-12-25 02:25
First, I want to say thank you so much for this library - it's saved me countless hours setting up and maintaining my own Chat UI. 

I faced this crash today with duplicate IDs as well and it took me quite a while to debug since I didn't know to look for that. It would be wonderful to have an assertionFailure, etc where if a duplicate ID is present in the messages collection, the developer is alerted

**Comment by f3dm76** [comment] 2023-12-25 14:38
Hey @froggomad I added the fatalError for duplicate ids in version 1.3.3, please check it out. I'm not happy with it, since it brings additional complexity, but I see it is needed. Have a great day!

**Comment by froggomad** [comment] 2024-01-04 02:49
Hey @f3dm76 thanks for responding and making the change so quickly! FatalError is great in that devs will definitely be notified if there's a problem 😄 

The reason I suggested `assertionFailure` is because it will only crash in -Onone (debug), while in -O (production) it's stripped. That way in the off chance there's a problem a dev didn't notice in debug, it doesn't crash the app in prod

**Comment by f3dm76** [comment] 2024-01-04 02:51
I think this is a kind of problem much better noticed in dev, than be left in prod - that's would be a catastrophe. Anyway I think I can close this now then. Have a wonderful day!

**Closed by f3dm76** 2024-01-04 02:51 UTC
