### ISSUE TITLE
Exyte Chat Crashing After 'DidSendMessage'

### ISSUE THREAD

**Issue by avjobcase** [exyte/Chat#21] opened 2023-05-22 17:10 UTC
## Summary
Exyte Chat will throw an exemption after sending a message through the chat input text field.

## Source of the Issue
The following exemption is thrown, and it is caused due to the TableView not having any cells to for which to render after `NotificationCenter.default.post(name: .onScrollToBottom, object: nil)` was called upon.
```
Attempted to scroll the table view to an out-of-bounds section (0) when there are only 0 sections
```

## Notes
I noticed that Exyte Chat is using Notification Center to send `.scrollToBottom` event, and there is a timeout of `0.3`.
I wonder if there is a race condition happening here in which the data source is not updated on time for that scroll event to call the table view.

**Comment by f3dm76** [comment] 2023-05-30 06:40
Hey @avjobcase, thank you so much for bringing this to my attention. I'm happy to let you know the issue is fixed in version 0.0.4, please give it a try. Have a wonderful day!

**Closed by f3dm76** 2023-05-30 06:40 UTC
